### ISSUE TITLE
Sprint 1: Cafe 도메인 관련 DTO 클래스 record class 변환

### ISSUE THREAD

**Issue by rt3310** [CAFREE-dev/cafree-backend#10]
## Description
Cafe 도메인 관련 DTO 클래스들을 record class로 변환

## To-do
- [x] CafeRegisterRequest 클래스 타입 변환 -> record
- [x] CafeUpdateRequest 클래스 타입 변환 -> record
- [x] CafeResponse 클래스 타입 변환 -> record
- [x] SimpleCafeResponse 클래스 타입 변환 -> record

## ETC
- 관련 링크
  - [https://www.digitalocean.com/community/tutorials/java-records-class](https://www.digitalocean.com/community/tutorials/java-records-class)
  - [https://www.baeldung.com/java-record-keyword](https://www.baeldung.com/java-record-keyword)
