### ISSUE TITLE
Sprint5: Cafe Domain 관련 추가 API 구현

### ISSUE THREAD

**Issue by lcomment** [CAFREE-dev/cafree-backend#30]
## Description

> 카페 도메인 관련 추가적인 기능 구현

## To-do

- [ ] 태그로 검색
- [ ] 조회 순으로 검색
- [ ] 거리 순으로 검색
- [ ] 컨셉 별로 검색
- [ ] 등록할 카페 목록 조회

## ETC

없음
